main: dev.cloudybyte.mcstatus.MCstatus
name: MCstatus
author: cloudybyte
version: 0.1.1
description: This plugin provides a rest api to get the current players, information about them and playercount.
api-version: "1.16"